export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];

export const crops = [
  "Absinthe",
  "Ajwan",
  "Alasande Gram",
  "Almond(Badam)",
  "Alsandikai",
  "Amaranthus",
  "Ambada Seed",
  "Ambady/Mesta",
  "Amla(Nelli Kai)",
  "Amphophalus",
  "Amranthas Red",
  "Antawala",
  "Anthurium",
  "Apple",
  "Apricot(Jardalu/Khumani)",
  "Arecanut(Betelnut/Supari)",
  "Arhar (Tur/Red Gram)(Whole)",
  "Arhar Dal(Tur Dal)",
  "Asalia",
  "Asgand",
  "Ashgourd",
  "Ashoka",
  "Ashwagandha",
  "Asparagus",
  "Astera",
  "Atis",
  "Avare Dal",
  "Bael",
  "Bajji chilli",
  "Bajra(Pearl Millet/Cumbu)",
  "Balekai",
  "Balsam",
  "Bamboo",
  "Banana",
  "Banana - Green",
  "Banana flower",
  "Banana Leaf",
  "Banana stem",
  "Barley (Jau)",
  "Basil",
  "Bay leaf (Tejpatta)",
  "Beans",
  "Beaten Rice",
  "Beetroot",
  "Behada",
  "Bengal Gram Dal (Chana Dal)",
  "Bengal Gram(Gram)(Whole)",
  "Ber(Zizyphus/Borehannu)",
  "Betal Leaves",
  "Betelnuts",
  "Bhindi(Ladies Finger)",
  "Bhui Amlaya",
  "Big Gram",
  "Binoula",
  "Bitter gourd",
  "Black Gram (Urd Beans)(Whole)",
  "Black Gram Dal (Urd Dal)",
  "Black pepper",
  "BOP",
  "Borehannu",
  "Bottle gourd",
  "Brahmi",
  "Bran",
  "Bread Fruit",
  "Brinjal",
  "Broccoli",
  "Broken Rice",
  "Broomstick(Flower Broom)",
  "Bull",
  "Bullar",
  "Bunch Beans",
  "Butter",
  "Buttery",
  "Cabbage",
  "Calendula",
  "Calf",
  "Camel Hair",
  "Cane",
  "Capsicum",
  "Cardamoms",
  "Carnation",
  "Carrot",
  "Cashew Kernnel",
  "Cashewnuts",
  "Castor Oil",
  "Castor Seed",
  "Cauliflower",
  "Chakotha",
  "Chandrashoor",
  "Chapparad Avare",
  "Chennangi (Whole)",
  "Chennangi Dal",
  "Cherry",
  "Chikoos(Sapota)",
  "Chili Red",
  "Chilly Capsicum",
  "Chironji",
  "Chow Chow",
  "Chrysanthemum",
  "Chrysanthemum(Loose)",
  "Cinnamon(Dalchini)",
  "Cineraria",
  "Clarkia",
  "Cloves",
  "Cluster beans",
  "Coca",
  "Cock",
  "Cocoa",
  "Coconut",
  "Coconut Oil",
  "Coconut Seed",
  "Coffee",
  "Colacasia",
  "Copra",
  "Coriander(Leaves)",
  "Coriander seed",
  "Cossandra",
  "Cotton",
  "Cotton Seed",
  "Cow",
  "Cowpea (Lobia/Karamani)",
  "Cowpea(Veg)",
  "Cucumber(Kheera)",
  "Cumin Seed(Jeera)",
  "Curry Leaf",
  "Custard Apple (Sharifa)",
  "Daila(Chandni)",
  "Dal (Avare)",
  "Dalda",
  "Delha",
  "Dhaincha",
  "Dhawai flowers",
  "Dianthus",
  "Double Beans",
  "Dragon fruit",
  "Dried mango",
  "Drumstick",
  "Dry Chillies",
  "Dry Fodder",
  "Dry Grapes",
  "Duck",
  "Duster Beans",
  "Egg",
  "Egyptian Clover(Barseem)",
  "Elephant Yam (Suran)",
  "Field Pea",
  "Fig(Anjura/Anjeer)",
  "Firewood",
  "Fish",
  "Flax seeds",
  "Flower Broom",
  "Foxtail Millet(Navane)",
  "French Beans (Frasbean)",
  "Galgal(Lemon)",
  "Gamphrena",
  "Garlic",
  "Ghee",
  "Giloy",
  "Gingelly Oil",
  "Ginger(Dry)",
  "Ginger(Green)",
  "Gladiolus Bulb",
  "Gladiolus Cut Flower",
  "Glardia",
  "Goat",
  "Goat Hair",
  "Golden rod",
  "Gond",
  "Gooseberry (Nellikkai)",
  "Gram Raw(Chholia)",
  "Gramflour",
  "Grapes",
  "Green Avare (W)",
  "Green Chilli",
  "Green Fodder",
  "Green Gram (Moong)(Whole)",
  "Green Gram Dal (Moong Dal)",
  "Green Peas",
  "Ground Nut Oil",
  "Ground Nut Seed",
  "Groundnut",
  "Groundnut (Split)",
  "Groundnut pods (raw)",
  "Guar",
  "Guar Seed(Cluster Beans Seed)",
  "Guava",
  "Gudmar",
  "Guggal",
  "Gulli",
  "Gur(Jaggery)",
  "Gurellu",
  "Gypsophila",
  "Haralekai",
  "Harrah",
  "He Buffalo",
  "Heliconia species",
  "Hen",
  "Hippe Seed",
  "Honey",
  "Honge seed",
  "Hybrid Cumbu",
  "Hydrangea",
  "Indian Beans (Seam)",
  "Indian Colza(Sarson)",
  "Irish",
  "Isabgul (Psyllium)",
  "Jack Fruit",
  "Jaee",
  "Jaffri",
  "Jaggery",
  "Jamamkhan",
  "Jamun(Narale Hannu)",
  "Jarbara",
  "Jasmine",
  "Javi",
  "Jowar(Sorghum)",
  "Jute",
  "Jute Seed",
  "Kabuli Chana(Chickpeas-White)",
  "Kacholam",
  "Kakada",
  "Kakatan",
  "Kalihari",
  "Kalmegh",
  "Kankambra",
  "Karamani",
  "Karanja seeds",
  "Karbuja(Musk Melon)",
  "Kartali (Kantola)",
  "Kevda",
  "Kharif Mash",
  "Khirni",
  "Khoya",
  "Kinnow",
  "Knool Khol",
  "Kodo Millet(Varagu)",
  "Kokum",
  "Kooth",
  "Kuchur",
  "Kulthi(Horse Gram)",
  "Kutki",
  "Ladies Finger",
  "Laha",
  "Lak(Teora)",
  "Leafy Vegetable",
  "Lemon",
  "Lentil (Masur)(Whole)",
  "Lilly",
  "Lime",
  "Limonia (status)",
  "Linseed",
  "Lint",
  "Liquor turmeric",
  "Litchi",
  "Little gourd (Kundru)",
  "Long Melon(Kakri)",
  "Lotus",
  "Lotus Sticks",
  "Lukad",
  "Lupine",
  "Ma.Inji",
  "Mace",
  "Macoy",
  "Mahedi",
  "Mahua",
  "Mahua Seed(Hippe seed)",
  "Maida Atta",
  "Maize",
  "Mango",
  "Mango (Raw-Ripe)",
  "Mango powder",
  "Maragensu",
  "Marasebu",
  "Marget",
  "Marigold(Calcutta)",
  "Marigold(loose)",
  "Marikozhunthu",
  "Mash",
  "Mushrooms",
  "Masur Dal",
  "Mataki",
  "Methi Seeds",
  "Methi(Leaves)",
  "Millets",
  "Mint(Pudina)",
  "Moath Dal",
  "Mousambi(Sweet Lime)",
  "Muesli",
  "Muleti",
  "Muskmelon Seeds",
  "Mustard",
  "Mustard Oil",
  "Myrobolan(Harad)",
  "Nargasi",
  "Nearle Hannu",
  "Neem Seed",
  "Nelli Kai",
  "Nerium",
  "Nigella seeds",
  "Niger Seed (Ramtil)",
  "Nutmeg",
  "Onion",
  "Onion Green",
  "Orange",
  "Orchid",
  "Other green and fresh vegetables",
  "Other Pulses",
  "Ox",
  "Paddy(Dhan)(Basmati)",
  "Paddy(Dhan)(Common)",
  "Palash flowers",
  "Papaya",
  "Papaya (Raw)",
  "Patti Calcutta",
  "Peach",
  "Pear(Marasebu)",
  "Peas cod",
  "Peas Wet",
  "Peas(Dry)",
  "Pigeon Pea (Arhar Fali)",
  "Pepper garbled",
  "Pepper ungarbled",
  "Perandai",
  "Persimon(Japani Fal)",
  "Pigs",
  "Pineapple",
  "Pippali",
  "Plum",
  "Pointed gourd (Parval)",
  "Polherb",
  "Pomegranate",
  "Poppy capsules",
  "Poppy seeds",
  "Potato",
  "Pumpkin",
  "Pundi",
  "Pundi Seed",
  "Pupadia",
  "Radish",
  "Ragi (Finger Millet)",
  "Raibel",
  "Rajgir",
  "Rala",
  "Ram",
  "Ramphal",
  "Rat Tail Radish (Mogari)",
  "Ratanjot",
  "Raya",
  "Rayee",
  "Red Cabbage",
  "Red gram Dal",
  "Resin",
  "Rice",
  "Ridgeguard(Turai)",
  "Rose",
  "Rose(Loose)",
  "Rubber",
  "Rubber Cake",
  "Safflower",
  "Safflower Seed",
  "Sago Seed",
  "Sal Seed",
  "Samai",
  "Sandalwood",
  "Sapota",
  "Sappotta",
  "Sarapgandha",
  "Seemebadnekai",
  "Sesame",
  "She Buffalo",
  "She Goat",
  "Sheep",
  "Sheep wool",
  "Shell",
  "Shirali",
  "Shivis",
  "Siddha Gulfa",
  "Silk",
  "Silk Cocoon",
  "Silver",
  "Simla Mirch",
  "Snake gourd",
  "Snow Peas",
  "Soapnut",
  "Sojna Munga",
  "Sonth",
  "Sorghum(Jowar)",
  "Soyabean",
  "Soyabean Oil",
  "Spinach",
  "Spiked ginger lily",
  "Spotted gourd",
  "Squash(vegetable marrow)",
  "Star Anise",
  "Stone",
  "Straw",
  "Strawberry",
  "Sugar",
  "Sugar Candy",
  "Sugarcane",
  "Sugarcane Seed",
  "Sunflower",
  "Sunflower Oil",
  "Sunflower Seed",
  "Sweet potato",
  "Sword beans",
  "Tamarind Fruit",
  "Tamarind Seed",
  "Tapioca",
  "Taro(Arvi)",
  "Tendli",
  "Tender Coconut",
  "Thali",
  "Thandlu",
  "Thelinia",
  "Thinner",
  "Thondi",
  "Thotakura",
  "Tiger Grass",
  "Tindla",
  "Tobacco",
  "Tomato",
  "Tooth Brush Bamboo",
  "Turmeric (Curcuma)",
  "Turmeric Polished",
  "Turnip",
  "Umbrella",
  "Urad dal",
  "Vanilla",
  "Vegetable Oil",
  "Vetiver Root",
  "Vinca",
  "Walnut",
  "Wheat",
  "Wheat Flour",
  "White Melon",
  "Wood Apple",
  "Wool",
  "Yam",
  "Yarn",
  "Yellow Peas",
  "Zinnia",
];
